/** @format */

export const ACCOUNT_BALANACE_REQUEST = 'ACCOUNT_BALANACE_REQUEST'
export const ACCOUNT_BALANACE_SUCCESS = 'ACCOUNT_BALANACE_SUCCESS'
export const ACCOUNT_BALANACE_FAIL = 'ACCOUNT_BALANACE_FAIL'

export const ACCOUNT_UPI_REQUEST = 'ACCOUNT_UPI_REQUEST'
export const ACCOUNT_UPI_SUCCESS = 'ACCOUNT_UPI_SUCCESS'
export const ACCOUNT_UPI_FAIL = 'ACCOUNT_UPI_FAIL'

export const ACCOUNT_BALANACE_UPDATE_REQUEST = 'ACCOUNT_BALANACE_UPDATE_REQUEST'
export const ACCOUNT_BALANACE_UPDATE_SUCCESS = 'ACCOUNT_BALANACE_UPDATE_SUCCESS'
export const ACCOUNT_BALANACE_UPDATE_FAIL = 'ACCOUNT_BALANACE_UPDATE_FAIL'
