/** @format */
export const ACCOUNT_INFO_REQUEST = 'ACCOUNT_INFO_REQUEST'
export const ACCOUNT_INFO_SUCCESS = 'ACCOUNT_INFO_SUCCESS'
export const ACCOUNT_INFO_FAIL = 'ACCOUNT_INFO_FAIL'

export const ACCOUNT_ADD_MONEY_REQUEST = 'ACCOUNT_ADD_MONEY_REQUEST'
export const ACCOUNT_ADD_MONEY_SUCCESS = 'ACCOUNT_ADD_MONEY_SUCCESS'
export const ACCOUNT_ADD_MONEY_FAIL = 'ACCOUNT_ADD_MONEY_FAIL'

export const ACCOUNT_BALANACE_REQUEST = 'ACCOUNT_BALANACE_REQUEST'
export const ACCOUNT_BALANACE_SUCCESS = 'ACCOUNT_BALANACE_SUCCESS'
export const ACCOUNT_BALANACE_FAIL = 'ACCOUNT_BALANACE_FAIL'

export const ACCOUNT_UPI_REQUEST = 'ACCOUNT_UPI_REQUEST'
export const ACCOUNT_UPI_SUCCESS = 'ACCOUNT_UPI_SUCCESS'
export const ACCOUNT_UPI_FAIL = 'ACCOUNT_UPI_FAIL'

export const ACCOUNT_BALANACE_UPDATE_REQUEST = 'ACCOUNT_BALANACE_UPDATE_REQUEST'
export const ACCOUNT_BALANACE_UPDATE_SUCCESS = 'ACCOUNT_BALANACE_UPDATE_SUCCESS'
export const ACCOUNT_BALANACE_UPDATE_FAIL = 'ACCOUNT_BALANACE_UPDATE_FAIL'
