/** @format */

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST'
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS'
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL'

export const TRANSACTION_SAVE_REQUEST = 'TRANSACTION_SAVE_REQUEST'
export const TRANSACTION_SAVE_SUCCESS = 'TRANSACTION_SAVE_SUCCESS'
export const TRANSACTION_SAVE_FAIL = 'TRANSACTION_SAVE_FAIL'
